services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: finsight-sqlserver
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      
    healthcheck:
      test: ["CMD", "bash", "-c", "</dev/tcp/localhost/1433"]
      interval: 30s
      timeout: 10s
      retries: 10

  backend:
    build:
      context: ./BackEnd/FinSight.api
      dockerfile: Dockerfile
    container_name: finsight-backend
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=finsight;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      sqlserver:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://backend:8080
    container_name: finsight-frontend
    ports:
      - "80:80"
    environment:
      - VITE_API_BASE_URL=http://backend:8080
    depends_on:
      - backend

volumes:
  sqlserver_data:
