import type { CashFlowType } from "./alphacompany";

const mockCashFlow: CashFlowType = {
    "symbol": "IBM",
    "annualReports": [
        {
            "fiscalDateEnding": "2024-12-31",
            "reportedCurrency": "USD",
            "operatingCashflow": "13445000000",
            "paymentsForOperatingActivities": "None",
            "proceedsFromOperatingActivities": "None",
            "changeInOperatingLiabilities": "None",
            "changeInOperatingAssets": "None",
            "depreciationDepletionAndAmortization": "4667000000",
            "capitalExpenditures": "1685000000",
            "changeInReceivables": "None",
            "changeInInventory": "-166000000",
            "profitLoss": "None",
            "cashflowFromInvestment": "-4937000000",
            "cashflowFromFinancing": "-7079000000",
            "proceedsFromRepaymentsOfShortTermDebt": "None",
            "paymentsForRepurchaseOfCommonStock": "None",
            "paymentsForRepurchaseOfEquity": "None",
            "paymentsForRepurchaseOfPreferredStock": "None",
            "dividendPayout": "6147000000",
            "dividendPayoutCommonStock": "6147000000",
            "dividendPayoutPreferredStock": "None",
            "proceedsFromIssuanceOfCommonStock": "None",
            "proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet": "None",
            "proceedsFromIssuanceOfPreferredStock": "None",
            "proceedsFromRepurchaseOfEquity": "-651000000",
            "proceedsFromSaleOfTreasuryStock": "None",
            "changeInCashAndCashEquivalents": "None",
            "changeInExchangeRate": "None",
            "netIncome": "6023000000"
        },
        {
            "fiscalDateEnding": "2023-12-31",
            "reportedCurrency": "USD",
            "operatingCashflow": "13432000000",
            "paymentsForOperatingActivities": "None",
            "proceedsFromOperatingActivities": "None",
            "changeInOperatingLiabilities": "None",
            "changeInOperatingAssets": "None",
            "depreciationDepletionAndAmortization": "4381000000",
            "capitalExpenditures": "1918000000",
            "changeInReceivables": "None",
            "changeInInventory": "390000000",
            "profitLoss": "None",
            "cashflowFromInvestment": "-7070000000",
            "cashflowFromFinancing": "-6016000000",
            "proceedsFromRepaymentsOfShortTermDebt": "None",
            "paymentsForRepurchaseOfCommonStock": "None",
            "paymentsForRepurchaseOfEquity": "None",
            "paymentsForRepurchaseOfPreferredStock": "None",
            "dividendPayout": "6016000000",
            "dividendPayoutCommonStock": "6016000000",
            "dividendPayoutPreferredStock": "None",
            "proceedsFromIssuanceOfCommonStock": "None",
            "proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet": "None",
            "proceedsFromIssuanceOfPreferredStock": "None",
            "proceedsFromRepurchaseOfEquity": "-416000000",
            "proceedsFromSaleOfTreasuryStock": "None",
            "changeInCashAndCashEquivalents": "None",
            "changeInExchangeRate": "None",
            "netIncome": "6925000000"
        },
        {
            "fiscalDateEnding": "2022-12-31",
            "reportedCurrency": "USD",
            "operatingCashflow": "10435000000",
            "paymentsForOperatingActivities": "None",
            "proceedsFromOperatingActivities": "None",
            "changeInOperatingLiabilities": "None",
            "changeInOperatingAssets": "None",
            "depreciationDepletionAndAmortization": "4802000000",
            "capitalExpenditures": "1860000000",
            "changeInReceivables": "None",
            "changeInInventory": "71000000",
            "profitLoss": "None",
            "cashflowFromInvestment": "-4202000000",
            "cashflowFromFinancing": "-4958000000",
            "proceedsFromRepaymentsOfShortTermDebt": "None",
            "paymentsForRepurchaseOfCommonStock": "None",
            "paymentsForRepurchaseOfEquity": "None",
            "paymentsForRepurchaseOfPreferredStock": "None",
            "dividendPayout": "5948000000",
            "dividendPayoutCommonStock": "5948000000",
            "dividendPayoutPreferredStock": "None",
            "proceedsFromIssuanceOfCommonStock": "None",
            "proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet": "None",
            "proceedsFromIssuanceOfPreferredStock": "None",
            "proceedsFromRepurchaseOfEquity": "-407000000",
            "proceedsFromSaleOfTreasuryStock": "None",
            "changeInCashAndCashEquivalents": "None",
            "changeInExchangeRate": "None",
            "netIncome": "1639000000"
                },
    ],
    "quarterlyReports": []
};

export default mockCashFlow;
