name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and publish backend Docker image
        run: |
          docker build -t ghcr.io/rahulram12833/finsight-backend:latest -f BackEnd/FinSight.api/Dockerfile ./BackEnd/FinSight.api
          docker push ghcr.io/rahulram12833/finsight-backend:latest

      - name: Build and publish frontend Docker image
        run: |
          docker build --build-arg VITE_API_BASE_URL=http://backend:8080 -t ghcr.io/rahulram12833/finsight-frontend:latest -f FrontEnd/Dockerfile ./FrontEnd
          docker push ghcr.io/rahulram12833/finsight-frontend:latest
